# Generated by Django 5.2.8 on 2025-12-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0002_alter_product_slug_alter_tag_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="apps.tag"
            ),
        ),
    ]
