# Generated by Django 5.2.8 on 2025-12-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0003_alter_product_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="specifications",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
