# Generated by Django 5.2.8 on 2025-12-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0004_alter_product_specifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
