# Generated by Django 5.2.8 on 2025-12-04 12:39

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0005_alter_product_like_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name="product",
            name="short_description",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
